"use client";
import { Box, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from "@mui/material";
import type { CartaoPontoValue } from "@/domain/transcription/model";
import { cartaoWarnings } from "@/domain/warnings/derive-warnings";
import { WarningRow } from "@/components/review/warning-row";

const periodFor = (dates: string[]) => [...new Set(dates.map((date) => { const parts = date.split("/"); return parts.length === 3 ? `${parts[1]}/${parts[2]}` : date; }))].join(", ");
const labelFor = (kind: "IN" | "OUT") => kind === "IN" ? "Entrada" : "Saída";

export function CartaoTable({ value, onChange }: { value: CartaoPontoValue; onChange: (value: CartaoPontoValue) => void }) {
  const warnings = cartaoWarnings(value); let warningIndex = 0;
  return <Stack spacing={2} aria-label="Transcrição de cartão de ponto">{value.pages.map((page, pageIndex) => <Paper key={page.page} variant="outlined"><Box sx={{ px: 2, py: 1.25, borderBottom: 1, borderColor: "divider" }}><Typography variant="subtitle1" sx={{ fontWeight: 700 }}>Página {page.page}</Typography><Typography variant="body2" color="text.secondary">Período: {periodFor(page.days.map((day) => day.date_raw)) || "não identificado"}</Typography></Box><Table size="small"><TableHead><TableRow><TableCell>Data</TableCell><TableCell>Entrada</TableCell><TableCell>Entrada corrigida</TableCell><TableCell>Saída</TableCell><TableCell>Saída corrigida</TableCell></TableRow></TableHead><TableBody>{page.days.flatMap((day, dayIndex) => { const currentWarnings = warnings[warningIndex++] ?? []; const pairs = Array.from({ length: Math.max(1, Math.ceil(day.punches.length / 2)) }, (_, index) => [day.punches[index * 2], day.punches[index * 2 + 1]] as const); return pairs.map(([entry, exit], pairIndex) => <WarningRow key={`${page.page}-${dayIndex}-${pairIndex}`} warnings={currentWarnings}><TableCell>{pairIndex === 0 ? day.date_raw : ""}</TableCell>{([entry, exit] as const).flatMap((punch) => { const kind = punch?.kind ?? (punch === entry ? "IN" : "OUT"); const punchIndex = punch ? day.punches.indexOf(punch) : -1; return [<TableCell key={`${kind}-raw`}><TextField fullWidth label={labelFor(kind)} value={punch?.time_raw ?? ""} slotProps={{ input: { readOnly: true } }} size="small" /></TableCell>, <TableCell key={`${kind}-edit`}><TextField fullWidth label={`${labelFor(kind)} corrigida`} value={punch?.time_hhmm ?? ""} disabled={!punch} onChange={(event) => { if (punchIndex < 0) return; const next = structuredClone(value); next.pages[pageIndex]!.days[dayIndex]!.punches[punchIndex]!.time_hhmm = event.target.value; onChange(next); }} size="small" /></TableCell>]; })}</WarningRow>); })}</TableBody></Table></Paper>)}</Stack>;
}
