"use client";
import { Box, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from "@mui/material";
import type { HoleriteValue } from "@/domain/transcription/model";
import { holeriteWarnings } from "@/domain/warnings/derive-warnings";
import { WarningRow } from "@/components/review/warning-row";

export function HoleriteTable({ value, onChange }: { value: HoleriteValue; onChange: (value: HoleriteValue) => void }) {
  const warnings = holeriteWarnings(value);
  return <Stack spacing={2} aria-label="Transcrição de holerite">{value.pages.map((page, pageIndex) => <Paper key={page.page} variant="outlined"><Stack direction={{ xs: "column", sm: "row" }} spacing={1} sx={{ alignItems: { sm: "center" }, px: 2, py: 1.25, borderBottom: 1, borderColor: "divider" }}><Box sx={{ flex: 1 }}><Typography variant="subtitle1" sx={{ fontWeight: 700 }}>Página {page.page}</Typography><Typography variant="body2" color="text.secondary">Competência</Typography></Box><TextField label="Mês" value={page.month} onChange={(event) => { const next = structuredClone(value); next.pages[pageIndex]!.month = event.target.value; onChange(next); }} size="small" /><TextField label="Ano" value={page.year} onChange={(event) => { const next = structuredClone(value); next.pages[pageIndex]!.year = event.target.value; onChange(next); }} size="small" /></Stack><Table size="small"><TableBody><WarningRow warnings={warnings[pageIndex] ?? []}><TableCell colSpan={4} sx={{ p: 0, border: 0 }}><Table size="small"><TableHead><TableRow><TableCell>Código</TableCell><TableCell>Descrição</TableCell><TableCell>Referência</TableCell><TableCell>Valor</TableCell></TableRow></TableHead><TableBody>{page.fields.map((field, fieldIndex) => <TableRow key={fieldIndex}><TableCell>{field.code || "—"}</TableCell><TableCell>{field.label}</TableCell><TableCell>{field.reference || "—"}</TableCell><TableCell><TextField fullWidth label="Valor" value={field.value} onChange={(event) => { const next = structuredClone(value); next.pages[pageIndex]!.fields[fieldIndex]!.value = event.target.value; onChange(next); }} size="small" /></TableCell></TableRow>)}</TableBody></Table>{page.bases.length > 0 && <><Typography variant="subtitle2" sx={{ px: 2, pt: 2 }}>Bases de cálculo</Typography><Table size="small"><TableHead><TableRow><TableCell>Descrição</TableCell><TableCell>Valor</TableCell></TableRow></TableHead><TableBody>{page.bases.map((base, baseIndex) => <TableRow key={baseIndex}><TableCell>{base.label}</TableCell><TableCell><TextField fullWidth label="Valor" value={base.value} onChange={(event) => { const next = structuredClone(value); next.pages[pageIndex]!.bases[baseIndex]!.value = event.target.value; onChange(next); }} size="small" /></TableCell></TableRow>)}</TableBody></Table></>}</TableCell></WarningRow></TableBody></Table></Paper>)}</Stack>;
}
