"use client";
import { Alert, Button, Container, Stack, Typography } from "@mui/material";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import type { GetTranscriptionResponse, TranscriptionValue } from "@/domain/transcription/model";
import { CartaoTable } from "@/components/review/cartao-table";
import { HoleriteTable } from "@/components/review/holerite-table";
import { ReviewSplitView } from "@/components/review/review-split-view";
export default function ReviewPage() { const { id } = useParams<{ id: string }>(); const [response, setResponse] = useState<GetTranscriptionResponse>(); const [value, setValue] = useState<TranscriptionValue>(); const [message, setMessage] = useState<string>(); useEffect(() => { fetch(`/api/transcricoes/${id}`, { cache: "no-store" }).then((result) => result.json()).then((body: GetTranscriptionResponse) => { setResponse(body); if (body.status === "concluido") setValue(body.value); }).catch(() => setMessage("Não foi possível carregar a transcrição.")); }, [id]); const save = async () => { if (!value) return; const result = await fetch(`/api/transcricoes/${id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ value }) }); if (!result.ok) { const body = await result.json() as { erro?: string }; setMessage(body.erro ?? "A correção é inválida."); } else setMessage("Correções salvas."); }; if (!response) return <Container sx={{ py: 6 }}><Typography>Carregando…</Typography></Container>; if (response.status !== "concluido" || !value) return <Container sx={{ py: 6 }}><Alert severity="error">{response.status === "erro" ? response.erro : "A transcrição ainda está sendo processada."}</Alert></Container>; const cartao = response.tipo === "cartao-ponto"; return <Container maxWidth="xl" sx={{ py: 3 }}><Stack spacing={2}><Typography variant="h5">Revisar transcrição</Typography>{message && <Alert severity={message === "Correções salvas." ? "success" : "error"}>{message}</Alert>}<ReviewSplitView id={id}>{cartao ? <CartaoTable value={value as import("@/domain/transcription/model").CartaoPontoValue} onChange={setValue} /> : <HoleriteTable value={value as import("@/domain/transcription/model").HoleriteValue} onChange={setValue} />}<Stack direction="row" spacing={1} sx={{ mt: 2 }}><Button variant="contained" onClick={save}>Salvar correções</Button>{(["xlsx", "csv", "json"] as const).map((format) => <Button key={format} component="a" href={`/api/transcricoes/${id}/planilha?formato=${format}`}>Baixar {format.toUpperCase()}</Button>)}</Stack></ReviewSplitView></Stack></Container>; }
